#!/bin/bash

HEADER=$(cat <<HEADER
#include <stdio.h>
#define писать(...) printf(__VA_ARGS__)
HEADER
)

SUBS=$(cat <<SUBS
    ⌂→ℤmain
    «→(
    »→)
    ☹→{
    ☺→}
    “→\"
    ”→\"
    ।→;
    ←→=
    ℤ→int 
    ␊→\\\n
SUBS
)

NEW=$(cat <<NEW
    ≤→<=
    ≥→>=
    ≨→<
    ≩→>
    ﹪ℤ→%i
    ،→,
    ﹪→%
    ∀→for 
    ∆→++
    ∇→--
NEW
)

OCTAL=☰☱☲☳☴☵☶☷
DECIMAL=᠐᠑᠒᠓᠔᠕᠖᠗᠘᠙

numlist () {
  out='';i=0
  for char in $(sed "s/\(.\)/\1 \
/g" <<<$1); do
    out+=$"${char}→$((i++))\n"
  done
echo -e "$out"
}

used () {
  sed 's/^ *\([^→]*\)→\(.*\)$/s\/\1\/\2\/g;/g;' <<<"$1"
}

main () {
  # Get Юᓂ곧⎔ source file to compile + options to pass to gcc
  echo "⎔⎔ing $1 ..."
  source=$(cat $1)
  shift

  replacements+=$(used "$NEW")
  replacements+=$(used "$SUBS")
  replacements+=$(used "$(numlist $OCTAL)")
  replacements+=$(used "$(numlist $DECIMAL)")

  # octal digit escaping
  source="$(sed 's/⁌\(['"$OCTAL"']\)/\\\1/g;s/⁍//g;' <<<"$source")"

  csource="$HEADER"$'\n'"$(sed "${replacements}" <<<"$source")"

  if gcc $@ -xc <(echo "$csource"); then
    echo Done!
  fi
}

main $@
