#!/bin/bash

HEADER=$(cat <<HEADER
᛭ᛋᚴᛁᛒᛅ ≨stdio᛫h≩
᛭ᚱᛁᛋᛏᛅ писать«…» printf«ᚼᛚᚢᛏᛅᚱ»
᛭ᚱᛁᛋᛏᛅ получатзнак«» getchar«»
HEADER
)

SUBS=$(cat <<SUBS
    ⌂→ℤmain
    «→(
    »→)
    ☹→{
    ☺→}
    “→\"
    ”→\"
    ❝→\/*
    ❞→*\/
    ¦→,
    ।→;
    −→-
    ×→*
    ←→=
    ℤ→int 
    ␊→\\\n
SUBS
)

NEW=$(cat <<NEW
    ≤→<=
    ≥→>=
    ≨→<
    ≩→>
    ﹪ℤ→%i
    ﹪ቁምፊ→%c
    ،→,
    ﹪→%
    ¿→if
    ∀→for
    ∆→++
    ∇→--
    ቁምፊ→char
NEW
)

PRE=$(cat <<PRE
    ᛫→.
    …→...
    ᛭ᚱᛁᛋᛏᛅ→#define
    ᛭ᛋᚴᛁᛒᛅ→#include
    ᚼᛚᚢᛏᛅᚱ→__VA_ARGS__
PRE
)

OCTAL=☰☱☲☳☴☵☶☷
DECIMAL=᠐᠑᠒᠓᠔᠕᠖᠗᠘᠙

numlist () {
  out='';i=0
  for char in $(sed "s/\(.\)/\1 \
/g" <<<$1); do
    out+=$"${char}→$((i++))\n"
  done
echo -e "$out"
}

used () {
  sed 's/^ *\([^→]*\)→\(.*\)$/s\/\1\/\2\/g;/g;' <<<"$1"
}

ucn_ids () {
  for ident in $(LC_ALL=POSIX egrep '^#|int|char' <<<"$1" |LC_ALL=POSIX  egrep -o '[^ -~]*'); do
    rep=$(echo -n $(iconv -futf8 -tutf16be <<<$ident) | xxd -p | sed 's/\([0-9a-f]\{4\}\)/\\\\u\1/g')
    csource="$(sed "s/$ident/$rep/g" <<<"$csource")"
  done
}

main () {
  # Get Юᓂ곧⎔ source file to compile + options to pass to gcc
  echo "⎔⎔ing $1 ..."
  source=$(cat $1)
  shift

  replacements+=$(used "$PRE")
  replacements+=$(used "$NEW")
  replacements+=$(used "$SUBS")
  replacements+=$(used "$(numlist $OCTAL)")
  replacements+=$(used "$(numlist $DECIMAL)")

  # octal digit escaping
  source="$(sed 's/⁌\(['"$OCTAL"']\)/\\\1/g;s/⁍//g;' <<<"$source")"

  csource="$(sed "${replacements}" <<<"$HEADER"$'\n'"$source")"

  ucn_ids "$csource"

  if gcc $@ -fextended-identifiers -std=c99 -w -xc <(echo "$csource"); then
    echo Done!
  fi
}

main $@
